# Generated by Django 3.2 on 2022-08-01 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Battalions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('Roster_Id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BonusArtifactsOfPower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('Roster_Id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BonusPrayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('Roster_Id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BonusSpells',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('Roster_Id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BonusUniqueEnhancements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('Roster_Id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EndlessSpellsAndInvocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('Roster_Id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ImposingStrongHoldTerritories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TerritoriesId', models.IntegerField(default=0)),
                ('Name', models.TextField()),
                ('TerritoryType', models.TextField()),
                ('Upgraded', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MightyStrongholdTerritories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TerritoriesId', models.IntegerField(default=0)),
                ('Name', models.TextField()),
                ('TerritoryType', models.TextField()),
                ('Upgraded', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PathToGloryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='QuestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RosterId', models.IntegerField(default=0)),
                ('CurrentQuest', models.TextField()),
                ('QuestReward', models.TextField()),
                ('QuestProgress', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Stronghold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RosterId', models.IntegerField(default=0)),
                ('Name', models.TextField()),
                ('Barracks', models.TextField()),
                ('Imposing', models.BooleanField(default=False)),
                ('Mighty', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StrongholdTerritories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TerritoriesId', models.IntegerField(default=0)),
                ('Name', models.TextField()),
                ('TerritoryType', models.TextField()),
                ('Upgraded', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TheVault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RosterId', models.IntegerField(default=0)),
                ('Triumph', models.TextField()),
                ('Battalions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pathtoglory.battalions')),
                ('BonusArtifactsOfPower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pathtoglory.bonusartifactsofpower')),
                ('BonusPrayers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pathtoglory.bonusprayers')),
                ('BonusSpells', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pathtoglory.bonusspells')),
                ('BonusUniqueEnhancements', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pathtoglory.bonusuniqueenhancements')),
                ('EndlessSpellsAndInvocations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pathtoglory.endlessspellsandinvocations')),
            ],
        ),
        migrations.CreateModel(
            name='Territories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RosterId', models.IntegerField(default=0)),
                ('ImposingStrongHoldTerritories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pathtoglory.imposingstrongholdterritories')),
                ('MightyStrongholdTerritories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pathtoglory.mightystrongholdterritories')),
                ('StrongholdTerritories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pathtoglory.strongholdterritories')),
            ],
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Group_id_as_int', models.IntegerField(default=0)),
                ('PlayerName', models.TextField()),
                ('Faction', models.TextField()),
                ('RealmOfOrigin', models.TextField()),
                ('ArmyName', models.TextField()),
                ('Subfaction', models.TextField()),
                ('StartingSize', models.IntegerField()),
                ('User_id', models.IntegerField(default=0)),
                ('Glory', models.IntegerField()),
                ('Completed', models.BooleanField(default=False)),
                ('DateCreated', models.DateField()),
                ('Group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pathtoglory.pathtoglorygroup')),
            ],
        ),
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BattlesFought', models.IntegerField(default=0)),
                ('QuestCompleted', models.IntegerField(default=0)),
                ('VictoriesWon', models.IntegerField(default=0)),
                ('EnemyHereosSlain', models.IntegerField(default=0)),
                ('RosterId', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='pathtoglory.roster')),
            ],
        ),
    ]
