# Generated by Django 4.0.4 on 2022-05-31 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pathtoglory', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PathToGloryGroups',
        ),
    ]
