# Generated by Django 3.2 on 2022-08-03 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pathtoglory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thevault',
            old_name='RosterId',
            new_name='Roster_Id',
        ),
    ]
