# Generated by Django 3.2 on 2022-08-06 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pathtoglory', '0002_rename_rosterid_thevault_roster_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thevault',
            name='Battalions',
        ),
        migrations.RemoveField(
            model_name='thevault',
            name='BonusArtifactsOfPower',
        ),
        migrations.RemoveField(
            model_name='thevault',
            name='BonusPrayers',
        ),
        migrations.RemoveField(
            model_name='thevault',
            name='BonusSpells',
        ),
        migrations.RemoveField(
            model_name='thevault',
            name='BonusUniqueEnhancements',
        ),
        migrations.RemoveField(
            model_name='thevault',
            name='EndlessSpellsAndInvocations',
        ),
        migrations.AddField(
            model_name='battalions',
            name='Vault_Id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Battalions', to='pathtoglory.thevault'),
        ),
        migrations.AddField(
            model_name='bonusartifactsofpower',
            name='Vault_Id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='BonusArtifactsOfPower', to='pathtoglory.thevault'),
        ),
        migrations.AddField(
            model_name='bonusprayers',
            name='Vault_Id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='BonusPrayers', to='pathtoglory.thevault'),
        ),
        migrations.AddField(
            model_name='bonusspells',
            name='Vault_Id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='BonusSpells', to='pathtoglory.thevault'),
        ),
        migrations.AddField(
            model_name='bonusuniqueenhancements',
            name='Vault_Id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='BonusUniqueEnhancements', to='pathtoglory.thevault'),
        ),
        migrations.AddField(
            model_name='endlessspellsandinvocations',
            name='Vault_Id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='EndlessSpellsAndInvocations', to='pathtoglory.thevault'),
        ),
    ]
