# Generated by Django 4.0.4 on 2022-05-31 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pathtoglory', '0002_delete_pathtoglorygroups'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathToGloryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField()),
            ],
        ),
    ]
