# Generated by Django 4.0.4 on 2022-06-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathtoglory', '0002_rename_iscompleted_roster_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roster',
            name='Achievements',
        ),
        migrations.RemoveField(
            model_name='roster',
            name='questlog',
        ),
        migrations.RemoveField(
            model_name='roster',
            name='Stronghold',
        ),
        migrations.RemoveField(
            model_name='roster',
            name='Territories',
        ),
        migrations.RemoveField(
            model_name='roster',
            name='Vault',
        ),
        migrations.AddField(
            model_name='achievements',
            name='RosterId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imposingstrongholdterritories',
            name='TerritoriesId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mightystrongholdterritories',
            name='TerritoriesId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questlog',
            name='RosterId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stronghold',
            name='RosterId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='strongholdterritories',
            name='TerritoriesId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='territories',
            name='RosterId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='thevault',
            name='RosterId',
            field=models.IntegerField(default=0),
        ),
    ]
