# Generated by Django 4.0.4 on 2022-06-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathtoglory', '0003_remove_roster_achievements_remove_roster_questlog_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roster',
            name='User',
        ),
        migrations.AddField(
            model_name='roster',
            name='User_Id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='roster',
            name='Glory',
            field=models.IntegerField(),
        ),
    ]
