# Generated by Django 3.2 on 2022-05-31 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathtoglory', '0004_rosters'),
    ]

    operations = [
        migrations.AddField(
            model_name='rosters',
            name='isCompleted',
            field=models.BooleanField(default=False),
        ),
    ]
