# Generated by Django 4.0.4 on 2022-07-01 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pathtoglory', '0004_remove_roster_user_roster_user_id_alter_roster_glory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roster',
            old_name='User_Id',
            new_name='User_id',
        ),
    ]
