# Generated by Django 4.0.4 on 2022-07-15 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pathtoglory', '0005_rename_user_id_roster_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='RosterId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pathtoglory.roster'),
        ),
    ]
