# Generated by Django 4.0.4 on 2022-09-28 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pathtoglory', '0005_hero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('Warscroll', models.TextField()),
                ('VeteranAbilities_Notes', models.TextField()),
                ('Reinforced1', models.BooleanField(default=False)),
                ('Reinforced2', models.BooleanField(default=False)),
                ('CasualtyScore', models.IntegerField(default=0)),
                ('RenownPoints', models.IntegerField(default=0)),
                ('Points', models.IntegerField(default=0)),
                ('OrderOfBattle', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Unit', to='pathtoglory.orderofbattle')),
            ],
        ),
    ]
