# Generated by Django 4.0.4 on 2022-07-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathtoglory', '0006_alter_achievements_rosterid'),
    ]

    operations = [
        migrations.AddField(
            model_name='roster',
            name='Group_id_as_int',
            field=models.IntegerField(default=0),
        ),
    ]
