# Generated by Django 4.0.7 on 2023-09-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathtoglory', '0006_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='territories',
            name='ImposingStrongHoldTerritories',
        ),
        migrations.RemoveField(
            model_name='territories',
            name='MightyStrongholdTerritories',
        ),
        migrations.RemoveField(
            model_name='territories',
            name='StrongholdTerritories',
        ),
        migrations.AddField(
            model_name='stronghold',
            name='Notes',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='ImposingStrongHoldTerritories',
        ),
        migrations.DeleteModel(
            name='MightyStrongholdTerritories',
        ),
        migrations.DeleteModel(
            name='StrongholdTerritories',
        ),
        migrations.DeleteModel(
            name='Territories',
        ),
    ]
