# Generated by Django 3.2 on 2022-05-31 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pathtoglory', '0006_auto_20220531_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlayerName', models.TextField()),
                ('Faction', models.TextField()),
                ('RealmOfOrigin', models.TextField()),
                ('ArmyName', models.TextField()),
                ('Subfaction', models.TextField()),
                ('StartingSize', models.IntegerField()),
                ('IsCompleted', models.BooleanField(default=False)),
                ('DateCreated', models.DateField()),
                ('Group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pathtoglory.pathtoglorygroup')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Rosters',
        ),
    ]
