# Generated by Django 4.0.7 on 2023-09-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathtoglory', '0007_remove_territories_imposingstrongholdterritories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stronghold',
            name='Upgraded',
            field=models.BooleanField(default=False),
        ),
    ]
