# Generated by Django 3.2 on 2022-05-31 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathtoglory', '0007_auto_20220531_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='roster',
            name='Glory',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
