# Generated by Django 4.0.4 on 2022-07-27 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pathtoglory', '0007_roster_group_id_as_int'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='BattlesFought',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='achievements',
            name='EnemyHereosSlain',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='achievements',
            name='QuestCompleted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='achievements',
            name='RosterId',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='pathtoglory.roster'),
        ),
        migrations.AlterField(
            model_name='achievements',
            name='VictoriesWon',
            field=models.IntegerField(default=0),
        ),
    ]
