# Generated by Django 4.0.4 on 2022-06-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathtoglory', '0008_roster_glory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roster',
            name='Glory',
            field=models.IntegerField(default=0),
        ),
    ]
