# Generated by Django 4.0.4 on 2022-07-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathtoglory', '0008_alter_achievements_battlesfought_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='battalions',
            name='Roster_Id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='battalions',
            name='User_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bonusartifactsofpower',
            name='Roster_Id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bonusartifactsofpower',
            name='User_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bonusprayers',
            name='Roster_Id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bonusprayers',
            name='User_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bonusspells',
            name='Roster_Id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bonusspells',
            name='User_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bonusuniqueenhancements',
            name='Roster_Id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bonusuniqueenhancements',
            name='User_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='endlessspellsandinvocations',
            name='Roster_Id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='endlessspellsandinvocations',
            name='User_id',
            field=models.IntegerField(default=0),
        ),
    ]
