# Generated by Django 4.0.7 on 2023-10-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathtoglory', '0008_stronghold_upgraded'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Roster_Id', models.IntegerField(default=0)),
                ('hero_phase', models.BooleanField(default=False)),
                ('movement_phase', models.BooleanField(default=False)),
                ('shooting_phase', models.BooleanField(default=False)),
                ('combat_phase', models.BooleanField(default=False)),
                ('general', models.BooleanField(default=False)),
                ('note', models.TextField()),
            ],
        ),
    ]
