# Generated by Django 4.0.4 on 2022-07-28 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pathtoglory', '0009_battalions_roster_id_battalions_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battalions',
            name='User_id',
        ),
        migrations.RemoveField(
            model_name='bonusartifactsofpower',
            name='User_id',
        ),
        migrations.RemoveField(
            model_name='bonusprayers',
            name='User_id',
        ),
        migrations.RemoveField(
            model_name='bonusspells',
            name='User_id',
        ),
        migrations.RemoveField(
            model_name='bonusuniqueenhancements',
            name='User_id',
        ),
        migrations.RemoveField(
            model_name='endlessspellsandinvocations',
            name='User_id',
        ),
    ]
