# Generated by Django 4.0.7 on 2023-10-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathtoglory', '0009_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='title',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
