# Generated by Django 4.0.4 on 2022-05-31 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Groups',
        ),
    ]
